plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'


    //testImplementation platform('org.junit:junit-bom:5.10.0')
    //testImplementation 'org.junit.jupiter:junit-jupiter'
    //testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.testng:testng:7.11.0'

    testImplementation 'org.seleniumhq.selenium:selenium-java:4.18.1'
    //implementation 'org.seleniumhq.selenium:selenium-devtools-v148:4.18.1'
    testImplementation 'org.seleniumhq.selenium:selenium-remote-driver:4.18.1'

    testImplementation 'org.slf4j:slf4j-api:2.0.16'
    testRuntimeOnly 'ch.qos.logback:logback-classic:1.5.17'
    //  для тестирования API
    testImplementation 'io.rest-assured:rest-assured:5.4.0'
}

test {
    useJUnitPlatform()

}